version: '3'

services:
  webserver:
    build:
      context: ./../
      dockerfile: docker/webserver/Dockerfile
    image: akeskimo/docker-registry:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../src/webserver:/app/
  cube:
    image: cubejs/cube:latest
    expose:
      - 4000  # Cube.js API
    ports:
      - 3000:3000  # Playground web server (available in dev mode, only)
    env_file: ./cubejs/.env
    volumes:
      - ./cubejs/schema:/cube/conf/schema
  postgres:
    shm_size: 256mb
    image: postgres
    restart: always
    env_file: ./postgres/.env
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
