version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../src/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../secrets:/etc/secrets/ssl
  rethmeter:
    build: ./webserver
    image: akeskimo/docker-registry:latest
    container_name: webserver
    restart: unless-stopped
    expose:
      - 3838
    volumes:
      - ../src/webserver:/srv/webserver/
      - ../log/:/var/log/rethmeter/
