version: '3'

services:
  webserver:
    container_name: webserver
    build:
      context: ./../
      dockerfile: docker/webserver/Dockerfile
    image: akeskimo/docker-registry:latest
    restart: unless-stopped
    ports:
      - 80:8000
    volumes:
      - ../src/webserver:/app
    depends_on:
      - "postgres"
  broker:
    container_name: broker
    build:
      dockerfile: docker/broker/Dockerfile
      context: ./../
    restart: always
    ports:
      - 4321:4321
    depends_on:
      - "webserver"
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3000:3000  # Playground web server (available in dev mode, only)
    env_file: ./cubejs/.env
    volumes:
      - ./cubejs/schema:/cube/conf/schema
    depends_on:
      - "postgres"
  postgres:
    shm_size: 256mb
    image: postgres
    restart: always
    env_file: ./postgres/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
